config/routes.rb
Botonera::Application.routes.draw do

  resources :contacts

  resources :visits
  resources :categories
  resources :users
  resources :sessions
  resources :articles

  get 'cadastrar', :to => 'users#new', :as => 'signup'
  get 'entrar', :to => 'sessions#new', :as => 'login'
  get 'sair', :to => 'sessions#destroy', :as => 'logout'
  get 'teste', :to => 'application#teste'

  # rotas para melhorar as URLs da aplicação
  match 'contato', :to =>'contacts#new', :as => 'contato', :menu => "contato"
  match 'private', :to =>'buttons#private', :as => 'private', :menu => "private"
  match 'count_visit', :to =>'visits#count_visit', :as => 'count_visit'
  match 'count_play', :to =>'buttons#count_play', :as => 'count_play'
  match 'melhores', :to =>'buttons#best_ever', :as => 'melhores', :menu => "melhores"
  match 'novo_blah', :to =>'buttons#new', :as => 'novo_blah', :menu => "novo_blah"
  match 'view', :to =>'buttons#view', :as => 'view'
  match 'manage_favorite', :to =>'buttons#manage_favorite', :as => 'manage_favorite', :menu => "favoritos"
  match 'favoritos', :to =>'buttons#favorites', :as => 'favoritos', :menu => "favoritos"
  match 'ranking', :to =>'users#ranking', :as => 'ranking', :menu => "ranking"


  # rotas temporárias para executar atualizações nos modelos
  match 'generate_share_code', :to =>'application#generate_share_code'
  match 'update_button_with_share_code', :to =>'application#update_button_with_share_code'
  match 'generate_nickname', :to =>'application#generate_nickname'

  # A ordem deve ser mantida para simular o permalink das categorias na listagem dos botões
  match 'categoria/:category' => 'buttons#index'
  resources :buttons

  root :to => 'buttons#index', :menu => "/"

end

app/models/button.rb
class Button < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_one :count
  has_many :favorites

  has_attached_file :media

  validates_presence_of :category_id
  validates_presence_of :title
  validates_attachment_presence :media, :message => I18n.t("paperclip.errors.media_presence")

  #validates_attachment_content_type :media, :content_type => ['audio/mp3', 'application/x-mp3'], :if => :media_attached?
  validates_format_of :media_file_name, :with => %r{\.(mp3)$}i, :message => I18n.t("paperclip.errors.media_format"), :if => :media_attached?
  validates_attachment_size :media, :less_than => 1.megabytes, :if => :media_attached?

  self.per_page = 28

  # Escopos
  scope :favoritos, lambda{|user_id| {
     :select=> "DISTINCT buttons.*",
     :joins=> "JOIN favorites ON (favorites.button_id = buttons.id) JOIN counts ON (counts.button_id = buttons.id) ",
     :conditions=> "favorites.user_id = #{user_id}",
     :order=> "counts.value DESC"
    }
  }

  scope :por_mais_tocados, lambda{ |order|
    joins("JOIN counts ON (counts.button_id = buttons.id) ").order("counts.value #{order}")
  }

  def get_msg
    I18n.t('activerecord.errors.messages.paperclip.size', :size=>1.megabyte)
  end

  def media_attached?
    self.media.file?
  end

  def is_favorite(user_id)
    !self.favorites.find_by_user_id(user_id).nil?
  end
end

app/controllers/buttons_controller.rb
# coding: utf-8
class ButtonsController < ApplicationController
  before_filter :authorize, :only=> [:new, :edit, :update, :favorites, :private]
  before_filter :verify_owner, :only=> [:show, :edit, :update]

  # GET /buttons
  # GET /buttons.json
  def index
    @category = nil
    order = params[:order] || "DESC"
    if params[:search] && !params[:search].to_s.empty?
      @buttons = Button.where("title like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page])
    else
      if params[:category]
        @category = Category.find_by_name(params[:category].gsub("+", " "))
        if @category
          @buttons = Button.page(params[:page]).order("created_at #{order}").find_all_by_category_id(@category.id)
        else
          @buttons = Button.where("title like ? or description like ?", "%#{params[:category]}%", "%#{params[:category]}%").page(params[:page])
        end
      else
        @buttons = Button.page(params[:page]).order("created_at #{order}").all
      end
    end

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render :json => @buttons }
    #end
  end

  # GET /buttons/1
  # GET /buttons/1.json
  def show
    @button = Button.find(params[:id])
    #gon.button = @button

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @button }
    end
  end

  # GET /buttons/new
  # GET /buttons/new.json
  def new
    @button = Button.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @button }
    end
  end

  # GET /buttons/1/edit
  def edit
    @button = Button.find(params[:id])
  end

  # POST /buttons
  # POST /buttons.json
  def create
    @button = Button.new(params[:button])
    @button.user_id=session[:user_id]
    @button.share_code=generate_share_code
    respond_to do |format|
      if @button.save
        format.html { redirect_to @button, :notice => t("messages.button_created") }
        format.json { render :json => @button, :status => :created, :location => @button }
      else
        format.html { render :action => "new" }
        format.json { render :json => @button.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /buttons/1
  # PUT /buttons/1.json
  def update
    @button = Button.find(params[:id])

    respond_to do |format|
      if @button.update_attributes(params[:button])
        format.html { redirect_to @button, :notice => t("messages.button_edited") }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @button.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /buttons/1
  # DELETE /buttons/1.json
  def destroy
    @button = Button.find(params[:id])
    @button.destroy

    respond_to do |format|
      format.html { redirect_to buttons_url }
      format.json { head :no_content }
    end
  end

  # Not RESTFUL Methods
  def count_play
      if params[:button_id]
        @count = Count.find_or_create_by_button_id(params[:button_id])
        value = @count.value

        if value
          @count.value=value+1
        else
          @count.value=1
        end
        @count.save

        respond_to do |format|
          format.html { render :text => "Button counted: #{@count.value}" }
          format.json { render :json => @count, :status => :ok}
        end
      end
  end

  def best_ever
    order = params[:order] || "DESC"
    @buttons = Button.por_mais_tocados(order).page(params[:page])
    respond_to do |format|
      format.html { render "index.html.erb" }
      format.json { render :json => @buttons, :status => :created}
    end
  end

  def favorites
    @buttons = Button.favoritos(session[:user_id]).page(params[:page])
    respond_to do |format|
      format.html { render "index.html.erb" }
      format.json { render :json => @buttons, :status => :created}
    end
  end

  def manage_favorite
    if !params[:button_id].nil? && session[:user_id]
      @button = Button.find(params[:button_id])
      if @button.is_favorite(session[:user_id])
        @favorite = Favorite.where("user_id = ? && button_id = ?",session[:user_id], params[:button_id]).first
        @favorite.destroy
      else
        @favorite = Favorite.new(:user_id => session[:user_id], :button_id => params[:button_id])
        @button.favorites << @favorite
        @button.save
      end
      respond_to do |format|
        format.html { render :text => "Button Favorite Status Changed: #{@button.title}" }
        format.json { render :json => @button, :status => :ok}
      end
    else
      respond_to do |format|
        format.html { head :no_content }
        format.json { head :no_content }
      end
    end
  end

  def view
    @button = Button.find_by_share_code(params[:b])

    respond_to do |format|
      format.html # view.html.erb
      format.json { render :json => @button }
    end
  end

  def private
    @buttons = Button.find_all_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # private.html.erb
      format.json { render :json => @buttons }
    end
  end

  def verify_owner
    @button = Button.find(params[:id])
    if (@button.user.id != session[:user_id])
      redirect_to root_url, :alert => "Não Autorizado"
    end
  end
end

app/helpers/buttons_helper.rb
module ButtonsHelper

  def player(button)

      html = ''
      html << "<div id='jquery_jplayer_1'></div>"
      html << "		<div class='jp-audio' button-id='#{button.id}'user-id='#{session[:user_id]}'>"
      html << "    			<div class='jp-type-single'>"
      html << "    				<div class='jp-gui jp-interface'>"
      html << "    					<ul id='button-#{button.id}' class='jp-controls'>"
      html << "    						<li><a href='#{button.media.url}' button-id='#{button.id}' class='jp-button jp-play-new' tabindex='1' >play</a></li>"
      html << "    					</ul>"
      html << "    				</div>"
      html << "    				<div id='title_#{button.id}' class='jp-title'>"
      html << "    					<ul>"
      html << "    						<li>#{button.title} <br/> #{t('player.plays')}: <span id='total_plays_#{button.id}'>#{(!button.count.nil? ? button.count.value : 0)}</span></li>"
      html << "    					</ul>"
      html << "    				</div>"

      link_label = t("player.add_favorites")
      favorite_state = 0
      if button.is_favorite(session[:user_id])
        link_label = t("player.remove_favorites")
        favorite_state = 1
      end
      html << "    				<div class='jp-function' id='function_#{button.id}' button-id='#{button.id}'>"
      html << "    				  <a href='#' favorite-state='#{favorite_state}' button-id='#{button.id}' id='favorite_link_#{button.id}' class='jp-function jp-function-favorite'>#{link_label}</a><hr />" if session[:user_id]
      html << "    				  <a href='/view/?b=#{button.share_code}' button-id='#{button.id}' id='favorite_link_#{button.id}' class='jp-function'>#{t('player.share')}</a>"
      html << "    				</div>"

      html << "    			</div>"
      html << "   </div>"

      html.html_safe

  end
end

app/views/buttons/_form.html.erb
<%= form_for(@button, :html => { :multipart => true }) do |f| %>
  <% if @button.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @button.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select(:category_id, Category.order("name").all.map {|c| [c.name, c.id]}, options ={:prompt => "Categoria"}, {:onchange=>"",:class=>"",:style=>"width: 217px; "})%>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :style=>"width: 210px; height: 50px;" %>
  </div>
  
  <% if @button.media? && !@button.media.dirty? %>
    <%= player @button %>
  <% end %>

  <br clear="all" />
  <br />
  <div class="field">
    <%= f.label :media %><br />
    <%= f.file_field :media %>
  </div>

  <div class="actions">
    <%= f.submit t("application.save"), :style=>"float:right;" %>
  </div>
  <br clear="all" />
<% end %>

app/views/buttons/edit.html.erb
<h1>Editar Botão</h1>

<%= render 'form' %>

<%= link_to 'Show', @button %> |
<%= link_to 'Back', buttons_path %>

app/views/buttons/index.html.erb
<% if !@buttons.nil? %>
    <% if @category %>
    <div class="right_text">
        <h2><%= @category.name %><br />
        <span> <%= @category.description %> </span>
        </h2>
    </div>
    <% end %>
    <p><%= will_paginate @buttons, :previous_label => t("navigation.previous"), :next_label => t("navigation.next") %> </p>
    <% @buttons.each do |button| %>
      <%=  player button %>
    <% end %>
    <br clear="all" />
    <p><%= will_paginate @buttons, :previous_label => t("navigation.previous"), :next_label => t("navigation.next") %></p>
<% else %>
    <div class="right_text">
        <h2>Atualize seu navegador. É necessário HTML5...</h2>
    </div>
<% end %>

<br clear="all" />
<br clear="all" />

<!--<%#= link_to 'New Button', new_button_path %>-->

app/views/buttons/new.html.erb
<h1><%= t("application.new") %> Blah</h1>

<%= render 'form' %>

<%#= link_to 'Back', buttons_path %>

app/views/buttons/private.html.erb
<% if !@buttons.nil? %>
    <div class="right_text">
        <h2>Listar Botões<br />
        <span> Gerencie seus botões </span>
        </h2>
    </div>
    <% @buttons.each do |button| %>
      <div style="float: left;">
        <%= player button %> <br />
        <div style="text-align: center; margin-bottom: 10px;"><%= link_to 'Editar', edit_button_path(button) %> | <%= link_to 'Apagar', button, :confirm => 'Tem certeza?', :method => :delete %></div>
      </div>
    <% end %>
<% else %>
    <div class="right_text">
        <h2>Not Found<br />
        <span> Please try again...</span>
        </h2>
    </div>
<% end %>

<br clear="all" />
<br clear="all" />

<!--<%#= link_to 'New Button', new_button_path %>-->

app/views/buttons/show.html.erb
<% if (@button.media?) %>
    Mídia Atual: <%= link_to @button.media_file_name, @button.media.url %><br /><br />

    <%= player(@button)  %>

<% end %>
<br clear="all"/>
<%= link_to 'Editar', edit_button_path(@button) %> |
<%= link_to 'Voltar', buttons_path %>

app/views/buttons/view.html.erb
<%
arrRequest = request.fullpath.split("&")
%>
<% content_for(:head) do %>
    <meta property="og:site_name" content="1Blah.com - <%= @button.title %>"/>
    <meta property="og:title" content="1Blah.com - <%= @button.title %>"/>
    <meta property="og:type" content="audio"/>
    <meta property="og:url" content="http://1blah.com<%= arrRequest[0] %>"/>
    <meta property="fb:app_id" content="190001861118360"/>
    <meta property="og:image" content="http://1blah.com/assets/logo.png"/>

    <meta property="og:audio" content="http://1blah.com<%= @button.media.url%>" />
    <meta property="og:audio:title" content="1Blah.com - <%= @button.title %>" />
    <meta property="og:audio:artist" content="1Blah.com - <%= @button.title %>" />
    <meta property="og:audio:album" content="1Blah.com - <%= @button.category.name %>" />
    <meta property="og:audio:type" content="<%= @button.media_content_type %>" />
    <meta property="og:description" content="Envie 1Blah para quem merece" />
<% end %>

<div class="right_text">
    <h2>Compartilhar<br />
    <span> Compartilhe seu Blah com amigos no Facebook ou Twitter.</span>
    </h2>
</div>

<div style="float: left;">
    <%= player @button %> <br />
</div>
<p>Clique no botão para enviar 1Blah pelo Twitter.</p>
<a href="https://twitter.com/intent/tweet?button_hashtag=1Blah&text=<%= @button.title %>" class="twitter-hashtag-button" data-lang="pt" data-size="large" data-url="http://1blah.com<%= request.fullpath %>">Tweet #1Blah</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<br />
<span style="font:normal 12px Arial, Helvetica, sans-serif; color:#606060; line-height:1.8em; padding:5px; margin:0;">Você pode copiar e colar a URL abaixo diretamente no seu Post no Facebook ou usar as ferramentas para enviar seu comentário diretamente da página 1Blah.com.</span>
<br />
<input type="text" value="http://1blah.com<%= arrRequest[0] %>" size="50" /><br />
<br clear="all" />
<p>Use o 1blah.com para postar sua vinheta no Facebook</p>
<div class="fb-like" data-send="true" data-width="450" data-show-faces="true"></div><br/>

<div class="fb-comments" data-href="http://1blah.com<%= arrRequest[0] %>" data-num-posts="5" data-width="470"></div>
<br clear="all" />