config/routes.rb
Botonera::Application.routes.draw do

  resources :contacts

  resources :visits
  resources :categories
  resources :users
  resources :sessions
  resources :articles

  get 'cadastrar', :to => 'users#new', :as => 'signup'
  get 'entrar', :to => 'sessions#new', :as => 'login'
  get 'sair', :to => 'sessions#destroy', :as => 'logout'
  get 'teste', :to => 'application#teste'

  # rotas para melhorar as URLs da aplicação
  match 'contato', :to =>'contacts#new', :as => 'contato', :menu => "contato"
  match 'private', :to =>'buttons#private', :as => 'private', :menu => "private"
  match 'count_visit', :to =>'visits#count_visit', :as => 'count_visit'
  match 'count_play', :to =>'buttons#count_play', :as => 'count_play'
  match 'melhores', :to =>'buttons#best_ever', :as => 'melhores', :menu => "melhores"
  match 'novo_blah', :to =>'buttons#new', :as => 'novo_blah', :menu => "novo_blah"
  match 'view', :to =>'buttons#view', :as => 'view'
  match 'manage_favorite', :to =>'buttons#manage_favorite', :as => 'manage_favorite', :menu => "favoritos"
  match 'favoritos', :to =>'buttons#favorites', :as => 'favoritos', :menu => "favoritos"
  match 'ranking', :to =>'users#ranking', :as => 'ranking', :menu => "ranking"


  # rotas temporárias para executar atualizações nos modelos
  match 'generate_share_code', :to =>'application#generate_share_code'
  match 'update_button_with_share_code', :to =>'application#update_button_with_share_code'
  match 'generate_nickname', :to =>'application#generate_nickname'

  # A ordem deve ser mantida para simular o permalink das categorias na listagem dos botões
  match 'categoria/:category' => 'buttons#index'
  resources :buttons

  root :to => 'buttons#index', :menu => "/"

end

app/models/visit.rb
class Visit < ActiveRecord::Base
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @visits }
    end
  end

  def count_visit
    now = DateTime.now.to_i

    if session[:user_id]
      user_id = session[:user_id]
    else
      user_id = 0
    end

    @visit = Visit.find_or_create_by_user_id(user_id)
    count = @visit.count

    if (session[:last_click] && session[:last_click] < (now - 60*5)) || !session[:last_click]
      if count
        @visit.count=count+1
      else
        @visit.count=1
      end
      @visit.save
      session[:last_click] = DateTime.now.to_i
    end
    @visit

    #respond_to do |format|
    #  format.html { render :text => "Aqui" }
    #  format.json { render :json => @visit, :status => :created, :location => @visit }
    #end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <tr>
    <th>User</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.user_id %></td>
    <td><%= visit.count %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @visit.user_id %>
</p>

<p>
  <b>Count:</b>
  <%= @visit.count %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>